### ISSUE TITLE
Appearance of minimap causes reflow in wide documents

### ISSUE THREAD

**Issue by wpowers** [djjcast/sublime-ToggleMinimapOnScroll#1]
Does it make sense to anyone and, if so, is it possible to have the minimap overlay the content, maybe with some kind of transparency? 

I often have wider files because I keep comments off to the right of the code and when I scroll in an area where I might have a longer comment, the appearance of the minimap causes the comment to break onto two lines and a jump in the document layout when its reflowed.

**Comment by djjcast** [comment]
Yes, it makes sense. I never noticed this issue because I disable word wrap.

Sublime Text's API doesn't expose a function to overlay the minimap or make it transparent. Although, I did figure out a way to simulate overlay when word wrap is enabled. This issue should be fixed in the latest version.

**Comment by ghost** [comment]
If

``` .json
{
    "draw_centered": true,
    "word_wrap": true
}
```

is set on, for example, Markdown Syntax Specific preferences, when scrolling, the Minimap works as expected but the text alignment still jumps a couple of characters to the left.
I usually just use Word Wrap in Markdown files so this was easy to spot... can `draw_centered` be the issue here?

**Comment by djjcast** [comment]
Yes, it seems like the draw_centered setting causes problems with this plugin. There is a similar issue with this plugin when the distraction free mode is enabled. Unfortunately, I don't think there is a way to solve this issue with the current API.

**Comment by ghost** [comment]
OK, thanks. I'll remove `draw_centered` or manually disable ToggleMinimapOnScroll (through command palette or shortcut) on those specific documents.
