### ISSUE TITLE
Hides minimap when scrolling, shows when not, if minimap is set disabled

### ISSUE THREAD

**Issue by AllanLRH** [djjcast/sublime-ToggleMinimapOnScroll#2]
The title says it all :)

If I disable the minimap (using the _View: Toggle Minimap_ from the Command palette) the minimap will show up when _not_ scrolling, and be hide during scrolling.

**Comment by djjcast** [comment]
That's the intended behavior. These are the behavior states:

```
If ToggleMinimapOnScroll is enabled:
    If the minimap is shown:
        The minimap is hidden when scrolling.
    If the minimap is hidden:
        The minimap is shown when scrolling.
If ToggleMinimapOnScroll is disabled:
    The minimap is either shown or hidden and scrolling does not affect it, e.g. the default behavior.
```

You can disable/enable ToggleMinimapOnScroll from the command palette using the _View: Disable/Enable ToggleMinimapOnScroll_ command.
