### ISSUE TITLE
Two or more columns/lines view

### ISSUE THREAD

**Issue by FrelEsquif** [djjcast/sublime-ToggleMinimapOnScroll#3]
Hi,

The plugin doesn't work properly when you have a layout with 2 or more columns/lines.
The minimap appears or disappears only when you scroll on the last file (the leftmost or downmost file).

Thank's for your work :-)

**Comment by djjcast** [comment]
Hello,

Sorry for taking so long to fix this issue. I forgot about it and just noticed it again today.

ToggleMinimapOnScroll now monitors all views for scroll events instead of only monitoring the active view.
