### ISSUE TITLE
Disable toggle_minimap on horizontal scroll

### ISSUE THREAD

**Issue by vengin** [djjcast/sublime-ToggleMinimapOnScroll#4]
I was wondering, if it might be possible to toggle minimap only on **vertical** scroll, not **horizontal** scroll.

Consider the following test case. There is a very long text, that doesn't fit into a single line of the current view (thus requiring horizontal scroll to view the different parts of the line). If one wants to move from the beginning of the line to the end (e.g. via pressing the `End` key), it will cause **horizontal** scroll, but the minimap will be toggled anyway, overlaying the actual end of the text line (which isn't useful). So, it might make seance to add some option like `toggle_minimap_disable_on_horizontal_scroll` to prevent this unwanted behavior.

I think it can be implemented with some kind of combination of `viewport_scrolled()` and `cursor_line_changed()` functions (i.e. `viewport_scrolled() == true  and  cursor_line_changed() == false`). Unfortunately, I'm not proficient in Python and not familiar with sublimetext package development environment. My attempts to play with the existing code weren't successful.

**Comment by djjcast** [comment]
Hello @vengin, does changing the following line
https://github.com/djjcast/sublime-ToggleMinimapOnScroll/blob/617a2abc3d806fed639a9937b045099c546b704f/ToggleMinimapOnScroll.py#L96 to

    prev_viewport_states[view_id]['viewport_position'][1] != viewport_position[1] and \
produce the expected behavior for you?

**Comment by vengin** [comment]
It does! Thanks a lot. I don't know if you want to add it as a feature, but it works for me.

**Comment by djjcast** [comment]
Okay, thanks for testing the change. You can now set `toggle_minimap_on_vertical_scroll_only` to true to have the minimap toggle only on vertical scroll.

**Comment by vengin** [comment]
Great. Thanks for quick response. Closing the issue.
